server:
  port: 8086

dubbo:
  registry:
    protocol: zookeeper
    address: zookeeper.gmall.com:2181
  protocol:
    name: dubbo
  application:
    name: gmall-order-web

spring:
  thymeleaf:
    mode: HTML
    cache: false
